### ISSUE TITLE
Hard coded ged file

### ISSUE THREAD

**Issue by kiwi3685** [magicsunday/ancestral-fan-chart#10]
Ric, you have your own ged file hard-coded in ancestral-fan-chart.js line 485:
'module.php?ged=Sonntag&mod=ancestral-fan-chart&mod_action=update&rootid=' + d.data.id + '&generations=' + that.options.generations

**Comment by magicsunday** [comment]
Ups :(

**Comment by magicsunday** [comment]
Fixed with 65f8b191da798406fc1d1fcef40449a593af8ad1
