### ISSUE TITLE
New option to hide empty segments

### ISSUE THREAD

**Issue by marku5** [magicsunday/ancestral-fan-chart#11]
Hello Rico,
one more idea to further improve your module, which one of the mostly used for my small tree. Thanks!!

Could you possibly add a confguration option to hide empty chart segments?
(Similar to 
http://www.syniumsoftware.com/de/macfamilytree/visualize -> Diagramme -> Top-right-picture)

BR, Markus

**Comment by magicsunday** [comment]
Fixed in master with commit f1c74353e85528cb3360d8e6a294fe7e7ce4eff4
