### ISSUE TITLE
Improve color of framework-lines

### ISSUE THREAD

**Issue by marku5** [magicsunday/ancestral-fan-chart#13]
Hallo Rico,

one m ore idea: The grey color of dividing lines look very much the same as sthe pink background of female anchestors. Could you in icrease the contracst of these two colors? E.g. dispay lines in white...

Thanks Markus

**Comment by magicsunday** [comment]
The colors are defined by the theme you are using.

**Comment by marku5** [comment]
OK, I've checked all themes and the dividing border is always light grey, whereas the fe-/male segments change their colour. So all theme-designer have choosen the same settings. Could you tell which CSS-setting controls this colour?

**Comment by magicsunday** [comment]
My fault. The border color of the arcs is defined by `#page-fan svg .arc path` in ancestral-fan-chart.css. Which theme you are using? On my page the colors for female ancestors and arc borders are quite different.

**Comment by marku5** [comment]
I like the xenea-theme. Please see the minimal difference betweenn boeder and pink segments.
![bildschirmfoto 2017-03-20 um 20 41 37](https://cloud.githubusercontent.com/assets/5243414/24118372/d2069f20-0dad-11e7-9d33-fe646c30d441.png)
