### ISSUE TITLE
Font size setting

### ISSUE THREAD

**Issue by kiwi3685** [magicsunday/ancestral-fan-chart#14]
Your version of the fan chart has an option to change the font size.
In the standard version the equivalent option changes the entire fan size.

Is that a deliberate choice, to change only the font size?

The problem is changing the font size (larger) doesn't really work well when the fan size remains the same. It would seem better if the entire fan AND the font size changed together, or perhaps remove that option?

**Comment by magicsunday** [comment]
The chart currently scales to the available screen width. I added this with https://github.com/magicsunday/ancestral-fan-chart/issues/3

Possibly, the percentage of the chart size should be selectable too.

**Comment by kiwi3685** [comment]
> The chart currently scales to the available screen width.

It "sort of" does. Certainly as you increase number of generations it enlarges, but at small number of generations (3?) it is very small and in no way scales to available screen width because the max-width calculation restrains it. It probably shouldn't fully fill available screen width then though. If you remove the 'max-width' restraint it goes much too big.

So yes, I think the ability to adjust total fan size would be good, with automatic adjustment to font sizes. For me that would be more useful than just adjusting font-size. Personally I would not use that option. I have in fact removed it from my installation.

**Comment by magicsunday** [comment]
> It "sort of" does. Certainly as you increase number of generations it enlarges, but at small number of generations (3?) it is very small and in no way scales to available screen width because the max-width calculation restrains it. It probably shouldn't fully fill available screen width then though. If you remove the 'max-width' restraint it goes much too big.

If you use a tablet for instance and 10 generations, the width of the chart will fit the max available width. I added the max-width constrain to prevent getting the scaled chart to big when displaying a small number of generations, which looks ugly too in my opinion.

**Comment by magicsunday** [comment]
Due the newly added zoom feature the max fan size will be the same as the max allowed size of the parent container. Also this keeps track of the responsive layout in webtrees 2.0. The font size just increases/decreases the size of the font if someone requires it.
