### ISSUE TITLE
Load additional ancestor data if clicked on a individual

### ISSUE THREAD

**Issue by magicsunday** [magicsunday/ancestral-fan-chart#17]
If displaying for instance a 3 generation chart and clicking on the parents of an individual the data of the next 3 generation should be loaded and displayed, not only the initial loaded data.

**Comment by mpwt** [comment]
It seems that it works like this with the recent master. I have tested and the chart loads the next generations when I clicking on a parent or other person.

**Comment by magicsunday** [comment]
My fault. :)
