### ISSUE TITLE
More than 10 generations

### ISSUE THREAD

**Issue by mishpochology** [magicsunday/ancestral-fan-chart#22]
Allow the maximum number of generations possible.

**Comment by magicsunday** [comment]
There will be not enough room for an 11th one as there will be no space left to display the names in a proper way.

**Comment by magicsunday** [comment]
Generating a chart with 25 generations means creating 33554432 entries for each possible individual and draw each of this 33554432 elements. This slow down your computer a lot. I dont think this make any sense at the moment.

**Comment by mishpochology** [comment]
Thanks anyway, and if you come across a software that can handle it let me
know.
Attached the tree I created in 2001.
Best regards
Salomon

[image: rashi_tree.jpg]

**Comment by magicsunday** [comment]
Your attachment is missing. :)
