### ISSUE TITLE
Size of input boxes for person ID and font size

### ISSUE THREAD

**Issue by mpwt** [magicsunday/ancestral-fan-chart#8]
Hallo, zuerst, es ist ein wunderbares Modul. Danke.

Kann es sein, dass die Größe des Eingabefeldes für die ID und die Schriftgröße etwas zu klein ist? Auf dem Tablet mit Safari wie auch mit Firefox unter MacOSX 10.9 sind die beiden Boxen etwas zu schmal für vier und mehr Zeichen.

**Comment by magicsunday** [comment]
Hm, dass kann ich so nicht nachvollziehen. Bei mir passen sogar 6 zeichen problemlos ins Eingabefeld rein. FF = 50.1 und iOS 10.2.1

![grafik](https://cloud.githubusercontent.com/assets/564393/22596422/c6864218-ea2b-11e6-971d-03965c1f42d5.png)

**Comment by mpwt** [comment]
Ah, sorry. Ich nutze Justlight und dort sieht es aktuell so aus:

![image](https://cloud.githubusercontent.com/assets/16311627/22603228/d04701c8-ea46-11e6-9b92-dadb9e78cf24.jpeg)

**Comment by magicsunday** [comment]
Gefixt durch ae52cf7770f00b12ac932e2561718fe179d5615c
