### ISSUE TITLE
Position of fan chart

### ISSUE THREAD

**Issue by mpwt** [magicsunday/ancestral-fan-chart#9]
Auf dem Tablet mit Safari fiel mir auf, dass bei 7 und mehr Generationen das Diagramm sichtbar nach rechts rutscht. Bei 6 oder weniger ist es genau zentriert. Reine Grafiksache ...

**Comment by magicsunday** [comment]
Das liegt daran, dass die Anzeigebreite im Hoch- bzw. Querformat nicht mehr ausreicht für die Größe des Diagramms. Ich muss mal gucken ob ich es skaliert bekomme, aber dann wird halt auch wieder schlecht lesbar denk ich.

**Comment by magicsunday** [comment]
Schau dir mal bitte die Anpassungen im Branch https://github.com/magicsunday/ancestral-fan-chart/tree/scale an. Passt das so mit der Skalierung?

**Comment by mpwt** [comment]
Also auf dem Tablet "ruckelt" jetzt nichts mehr. Sieht gut aus (Auswahlmenü ist jetzt zweizeilig). Am Desktop kann ich es heute nicht mehr probieren, aber da ist sowieso viel mehr Platz.

![image](https://cloud.githubusercontent.com/assets/16311627/22605959/54cde0f0-ea52-11e6-9285-7f6c9f981f8a.jpeg)

Vielen Dank. Wird wohl mein Lieblingsdiagramm ...

**Comment by magicsunday** [comment]
Änderungen in master-Branch übernommen.
